/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTickerRouteImport } from './routes/admin.ticker'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as AdminArticlesNewRouteImport } from './routes/admin.articles.new'
import { Route as AdminArticlesIdEditRouteImport } from './routes/admin.articles.$id.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTickerRoute = AdminTickerRouteImport.update({
  id: '/ticker',
  path: '/ticker',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminArticlesRoute,
} as any)
const AdminArticlesIdEditRoute = AdminArticlesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminArticlesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/ticker': typeof AdminTickerRoute
  '/admin/users': typeof AdminUsersRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/articles/$id/edit': typeof AdminArticlesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/ticker': typeof AdminTickerRoute
  '/admin/users': typeof AdminUsersRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/articles/$id/edit': typeof AdminArticlesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/ticker': typeof AdminTickerRoute
  '/admin/users': typeof AdminUsersRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/articles/$id/edit': typeof AdminArticlesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/search'
    | '/services'
    | '/terms'
    | '/admin/ads'
    | '/admin/articles'
    | '/admin/categories'
    | '/admin/subscribers'
    | '/admin/ticker'
    | '/admin/users'
    | '/article/$slug'
    | '/category/$slug'
    | '/admin/'
    | '/admin/articles/new'
    | '/admin/articles/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/search'
    | '/services'
    | '/terms'
    | '/admin/ads'
    | '/admin/articles'
    | '/admin/categories'
    | '/admin/subscribers'
    | '/admin/ticker'
    | '/admin/users'
    | '/article/$slug'
    | '/category/$slug'
    | '/admin'
    | '/admin/articles/new'
    | '/admin/articles/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/search'
    | '/services'
    | '/terms'
    | '/admin/ads'
    | '/admin/articles'
    | '/admin/categories'
    | '/admin/subscribers'
    | '/admin/ticker'
    | '/admin/users'
    | '/article/$slug'
    | '/category/$slug'
    | '/admin/'
    | '/admin/articles/new'
    | '/admin/articles/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ticker': {
      id: '/admin/ticker'
      path: '/ticker'
      fullPath: '/admin/ticker'
      preLoaderRoute: typeof AdminTickerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof AdminArticlesRoute
    }
    '/admin/articles/$id/edit': {
      id: '/admin/articles/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/articles/$id/edit'
      preLoaderRoute: typeof AdminArticlesIdEditRouteImport
      parentRoute: typeof AdminArticlesRoute
    }
  }
}

interface AdminArticlesRouteChildren {
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
  AdminArticlesIdEditRoute: typeof AdminArticlesIdEditRoute
}

const AdminArticlesRouteChildren: AdminArticlesRouteChildren = {
  AdminArticlesNewRoute: AdminArticlesNewRoute,
  AdminArticlesIdEditRoute: AdminArticlesIdEditRoute,
}

const AdminArticlesRouteWithChildren = AdminArticlesRoute._addFileChildren(
  AdminArticlesRouteChildren,
)

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminArticlesRoute: typeof AdminArticlesRouteWithChildren
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminTickerRoute: typeof AdminTickerRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminArticlesRoute: AdminArticlesRouteWithChildren,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminTickerRoute: AdminTickerRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
